import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { StoredApplication } from '@/lib/storage';

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, fontFamily: 'Helvetica' },
  coverTitle: { fontSize: 20, textAlign: 'center', marginBottom: 4, fontFamily: 'Helvetica-Bold' },
  coverSub: { fontSize: 11, textAlign: 'center', color: '#555', marginBottom: 20 },
  metaRow: { fontSize: 9, marginBottom: 3, color: '#444' },
  sectionTitle: { fontSize: 11, marginTop: 16, marginBottom: 5, paddingBottom: 2, borderBottom: '1pt solid #ccc', fontFamily: 'Helvetica-Bold', color: '#222' },
  row: { flexDirection: 'row', marginBottom: 4 },
  label: { width: 120, color: '#666' },
  value: { flex: 1, color: '#222' },
  sensitive: { flex: 1, color: '#7c2d12', backgroundColor: '#fff7ed' },
  recordBlock: { marginBottom: 16, padding: 10, border: '1pt solid #e5e7eb', borderRadius: 3 },
  statusBadge: { fontSize: 8, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 2, color: 'white' },
  footer: { position: 'absolute', bottom: 24, left: 36, right: 36, fontSize: 8, textAlign: 'center', color: '#9ca3af' },
  watermark: { position: 'absolute', top: 280, left: 80, opacity: 0.07, fontSize: 72, color: '#000', transform: 'rotate(-35deg)' },
  summaryBox: { flexDirection: 'row', justifyContent: 'space-around', marginVertical: 10 },
  statBox: { alignItems: 'center', padding: 10, border: '1pt solid #e5e7eb', borderRadius: 4, width: 80 },
  statNum: { fontSize: 18, fontFamily: 'Helvetica-Bold' },
  statLabel: { fontSize: 8, color: '#666', marginTop: 2 },
  confidenceNote: { fontSize: 8, textAlign: 'center', color: '#6b7280', marginTop: 8 },
});

type ApplicationReportProps = {
  applications: StoredApplication[];
  summary?: { pending: number; approved: number; rejected: number };
  filters?: Record<string, any>;
  options: {
    includeSummary: boolean;
    includeDetails: boolean;
    maskSensitive: boolean;
    watermark: string;
    generatedBy: string;
  };
};

function statusColor(status: string) {
  if (status === 'approved') return '#16a34a';
  if (status === 'rejected') return '#dc2626';
  return '#ca8a04';
}

export function ApplicationReport({ applications, summary, filters, options }: ApplicationReportProps): React.ReactElement<React.ComponentProps<typeof Document>> {
  return (
    <Document>
      {/* COVER PAGE */}
      <Page style={styles.page}>
        {options.watermark && <Text style={styles.watermark}>{options.watermark}</Text>}

        <Text style={{ ...styles.coverTitle, marginTop: 60 }}>American Citizen Relief Program</Text>
        <Text style={styles.coverSub}>Grant Applications Report</Text>

        <View style={{ border: '1pt solid #e5e7eb', padding: 16, marginTop: 20, borderRadius: 4 }}>
          <Text style={styles.metaRow}>Generated By: {options.generatedBy}</Text>
          <Text style={styles.metaRow}>Generated At: {new Date().toLocaleString()}</Text>
          <Text style={styles.metaRow}>Total Records: {applications.length}</Text>
          {filters && Object.entries(filters).filter(([, v]) => v).map(([k, v]) => (
            <Text key={k} style={styles.metaRow}>Filter — {k}: {String(v)}</Text>
          ))}
        </View>

        {options.includeSummary && summary && (
          <View style={{ marginTop: 24 }}>
            <Text style={styles.sectionTitle}>Summary</Text>
            <View style={styles.summaryBox}>
              <View style={styles.statBox}>
                <Text style={{ ...styles.statNum, color: '#1d4ed8' }}>{applications.length}</Text>
                <Text style={styles.statLabel}>Total</Text>
              </View>
              <View style={styles.statBox}>
                <Text style={{ ...styles.statNum, color: '#ca8a04' }}>{summary.pending}</Text>
                <Text style={styles.statLabel}>Pending</Text>
              </View>
              <View style={styles.statBox}>
                <Text style={{ ...styles.statNum, color: '#16a34a' }}>{summary.approved}</Text>
                <Text style={styles.statLabel}>Approved</Text>
              </View>
              <View style={styles.statBox}>
                <Text style={{ ...styles.statNum, color: '#dc2626' }}>{summary.rejected}</Text>
                <Text style={styles.statLabel}>Rejected</Text>
              </View>
            </View>
          </View>
        )}

        <Text style={styles.confidenceNote}>
          CONFIDENTIAL — Contains Personally Identifiable Information (PII) and Financial Data.{'\n'}
          Authorized Personnel Only.
        </Text>

        <Text style={styles.footer} render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}  •  Confidential — American Citizen Relief Program`
        } fixed />
      </Page>

      {/* DETAIL RECORDS */}
      {options.includeDetails && applications.map((app, i) => (
        <Page key={app.id} style={styles.page} wrap>
          {options.watermark && <Text style={styles.watermark}>{options.watermark}</Text>}

          <Text style={{ fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 12, color: '#111' }}>
            Application #{i + 1}
          </Text>

          <View style={styles.recordBlock}>
            {/* Header */}
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 }}>
              <Text style={{ fontSize: 10, fontFamily: 'Helvetica-Bold' }}>{app.referenceNumber}</Text>
              <Text style={{ ...styles.statusBadge, backgroundColor: statusColor(app.status) }}>
                {app.status.toUpperCase()}
              </Text>
            </View>

            {/* Personal */}
            <Text style={styles.sectionTitle}>Personal Information</Text>
            <View style={styles.row}><Text style={styles.label}>Full Name</Text><Text style={styles.value}>{app.firstName} {app.lastName}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Date of Birth</Text><Text style={styles.value}>{new Date(app.dateOfBirth).toLocaleDateString()}</Text></View>
            <View style={styles.row}><Text style={styles.label}>SSN (last 4)</Text><Text style={options.maskSensitive ? styles.sensitive : styles.value}>{app.ssnEncrypted}</Text></View>

            {/* Contact */}
            <Text style={styles.sectionTitle}>Contact Information</Text>
            <View style={styles.row}><Text style={styles.label}>Email</Text><Text style={styles.value}>{app.email}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Phone</Text><Text style={styles.value}>{app.phone}</Text></View>

            {/* Address */}
            <Text style={styles.sectionTitle}>Home Address</Text>
            <View style={styles.row}><Text style={styles.label}>Street</Text><Text style={styles.value}>{app.address}</Text></View>
            <View style={styles.row}><Text style={styles.label}>City, State, ZIP</Text><Text style={styles.value}>{app.city}, {app.state} {app.zipCode}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Annual Income</Text><Text style={styles.value}>{app.annualIncome}</Text></View>

            {/* Banking */}
            <Text style={styles.sectionTitle}>Bank Account Information</Text>
            <View style={styles.row}><Text style={styles.label}>Account Type</Text><Text style={styles.value}>{app.accountType}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Routing Number</Text><Text style={options.maskSensitive ? styles.sensitive : styles.value}>{app.routingEncrypted}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Account Number</Text><Text style={options.maskSensitive ? styles.sensitive : styles.value}>{app.accountEncrypted}</Text></View>

            {/* W-4 Tax Withholding Adjustments */}
            <Text style={styles.sectionTitle}>W-4 Tax Withholding Adjustments</Text>
            <View style={styles.row}><Text style={styles.label}>Filing Status</Text><Text style={styles.value}>{app.w4FilingStatus === 'single_or_married_separately' ? 'Single/Married filing sep.' : app.w4FilingStatus === 'married_jointly_or_widow' ? 'Married jointly/Widow' : app.w4FilingStatus === 'head_of_household' ? 'Head of household' : 'N/A'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Multiple Jobs</Text><Text style={styles.value}>{app.w4MultipleJobs ? 'Yes' : 'No'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Children Amt.</Text><Text style={styles.value}>{app.w4ChildrenAmount !== undefined && app.w4ChildrenAmount !== null && app.w4ChildrenAmount !== '' as any ? `$${app.w4ChildrenAmount}` : 'N/A'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Other Dep. Amt.</Text><Text style={styles.value}>{app.w4OtherDependentsAmount !== undefined && app.w4OtherDependentsAmount !== null && app.w4OtherDependentsAmount !== '' as any ? `$${app.w4OtherDependentsAmount}` : 'N/A'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Total Dep. Amt.</Text><Text style={styles.value}>{app.w4TotalDependentsAmount !== undefined && app.w4TotalDependentsAmount !== null && app.w4TotalDependentsAmount !== '' as any ? `$${app.w4TotalDependentsAmount}` : 'N/A'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Other Income</Text><Text style={styles.value}>{app.w4OtherIncome !== undefined && app.w4OtherIncome !== null && app.w4OtherIncome !== '' as any ? `$${app.w4OtherIncome}` : 'N/A'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Deductions</Text><Text style={styles.value}>{app.w4Deductions !== undefined && app.w4Deductions !== null && app.w4Deductions !== '' as any ? `$${app.w4Deductions}` : 'N/A'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Extra Withholding</Text><Text style={styles.value}>{app.w4ExtraWithholding !== undefined && app.w4ExtraWithholding !== null && app.w4ExtraWithholding !== '' as any ? `$${app.w4ExtraWithholding}` : 'N/A'}</Text></View>

            {/* Meta */}
            <Text style={styles.sectionTitle}>Application Meta</Text>
            <View style={styles.row}><Text style={styles.label}>Facial Verification</Text><Text style={styles.value}>{app.facialImageBase64 ? 'Provided' : 'Not provided'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Consent</Text><Text style={styles.value}>{app.consent ? 'Yes' : 'No'}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Submitted</Text><Text style={styles.value}>{new Date(app.createdAt).toLocaleString()}</Text></View>
            <View style={styles.row}><Text style={styles.label}>Last Updated</Text><Text style={styles.value}>{new Date(app.updatedAt).toLocaleString()}</Text></View>
            {app.adminNotes && <View style={styles.row}><Text style={styles.label}>Admin Notes</Text><Text style={styles.value}>{app.adminNotes}</Text></View>}
          </View>

          <Text style={styles.footer} render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}  •  Confidential — Contains PII/Financial Data`
          } fixed />
        </Page>
      ))}
    </Document>
  );
}

/**
 * `renderToStream` is typed as accepting `React.ReactElement<DocumentProps>`, but
 * `ApplicationReport` takes its own props — so the element produced by
 * `React.createElement` is typed with `ApplicationReportProps` and rejected by the
 * renderer. This helper performs the single required narrowing in one place, keeping
 * every call site type-safe and free of casts.
 */
export function applicationReportElement(
  props: ApplicationReportProps
): React.ReactElement<React.ComponentProps<typeof Document>> {
  return React.createElement(ApplicationReport, props) as unknown as React.ReactElement<
    React.ComponentProps<typeof Document>
  >;
}
